tools:
  external_code_coverage:
    timeout: 900    # Timeout in seconds.
filter:
  excluded_paths:
    - "tests/"
    # Everything in a root level "tests" directory will be excluded
  dependency_paths:
    - "vendor/"
    # Everything in a root level "lib" directory will be excluded from analysis
    # but treated as a dependency
