dist: bionic

language: php
php:
  - 7.2
  - 7.3

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - mkdir -p build/coverage

script:
  - composer travis

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/clover.xml
    fi

notifications:
  on_success: never
  on_failure: always

env:
  global:
    # secure key for infection badge (see https://infection.github.io/guide/mutation-badge.html)
    secure: VyW+SCaCArQZJJ6/zQy++jQkxkVLqbT390K6LZsIISADQ+I5SDzJ34VYLQxguO4lt/CC5U/hKqdqhwRdHKACrpdMO9rO7vD1Y+gU94gpyF+UT90Jx1RSRFi0pNQvKVgNTdT372vUvapZxgsTJaIhj8GpSi+nD2ZbIIm3nWSgTcRpJWB+0ldPiaijPbsaiF53VYNzxbsNZnXLMBkr2LcDbz4ggP5v5ETeAkI64c2gppdSoQQzd9qB2ViXKS6CvNrWK4PW6M/2PtcFwsutF4J/2N8PFr1PiYZ439nFP3dBJ7CDBnyWviA3D+hgHYEQlbm5ULmBLAY4reycD1cBdeUNDO4ImmmUvLn8pNa9g48qA1MQr75RMDCp8uEJaGgygfDSi1c4KDUAbvlGcawQMTKyULWaMQohUvzBp20gARBJ24ICde1N1b/7UAVW3GV4qNVFpSPvTOtNFNzHIkqhxxEapttg7bbqd0hAUuN5A7/itHs8sy7S5DwE5TmqVPEzXmryLktu7lZiPbblNDRh2NAzYW/DavvVLZrxLkdHYCLfoDA1XYBmlAG1Q49GLA0sGl76Kk/qbkaf7yPgwZXLYtX28FGEL1UukBZxo1ym75PogbPSbebiyqV+XB/7cpbx5muWq3zYF2i03X4ATsGX4O+c7/Ahg8g40pJFoPXKPgQ/IK0=
